config/routes.rb
Rails.application.routes.draw do

  resources :tiles, path: '/store/tiles'
  resources :shippers, path: '/store/shippers'
  resources :authentications
  get '/store/orders/carts' => 'orders#carts', :as => :carts
  get '/store/orders/details/:id' => 'orders#details', :as => :order_details
  get '/store/orders/invoice/:id' => 'orders#invoice', :as => :order_invoice
  get '/store/orders/invoice/:id/print' => 'orders#print', :as => :order_print
  get '/store/checkout/address-select' => 'checkouts#address_select', :as => :address_select
  get '/store/checkout/shipping-select' => 'checkouts#shipping_select', :as => :shipping_select
  get '/store/checkout/review' => 'checkouts#review', :as => :review
  get '/store/checkout/process-order' => 'checkouts#process_order', :as => :process_order
  get '/store/checkout/packaging' => 'checkouts#packaging', :as => :packaging
  get '/approved', to: redirect('approved.html'), :as => :approved_js
  get '/disapproved', to: redirect('disapproved.html'), :as => :disapproved_js
  get '/store/checkout/approved' => 'checkouts#approved', :as => :approved
  get '/store/checkout/disapproved' => 'checkouts#disapproved', :as => :disapproved
  post '/store/checkout/approved' => 'checkouts#approved_post', :as => :approved_post
  post '/store/checkout/disapproved' => 'checkouts#disapproved_post', :as => :disapproved_post
  get '/store/main' => 'products#main', :as => :store_main
  get '/store/products' => 'products#products', :as => :product_management
  get '/store/gun-parts' => 'products#gun_parts', :as => :gunparts
  get '/store/custom-parts' => 'products#custom_parts', :as => :custom_parts
  get '/store/wood' => 'products#wood', :as => :wood
  get '/store/barrels' => 'products#barrels', :as => :barrels
  get '/store/optics' => 'products#optics', :as => :optics
  get '/store/gifts' => 'products#gifts', :as => :gifts
  get '/store/jewlery' => 'products#jewelry', :as => :jewelry
  get '/store/decor' => 'products#decor', :as => :decor
  get '/store/gun-cases' => 'products#gun_cases', :as => :gun_cases
  get '/store/guns' => 'products#guns', :as => :guns
  get '/store/contact' => 'products#contact', :as => :store_contact
  get '/store/privacy-policy' => 'products#privacy_policy', :as => :privacy_policy
  get '/store/return-policy' => 'products#return_policy', :as => :return_policy
  get '/store/terms-and-conditions' => 'products#terms_and_conditions', :as => :terms_and_conditions
  get '/store/payment-policy' => 'products#payment_policy', :as => :payment_policy
  get '/store/shipping-policy' => 'products#shipping_policy', :as => :shipping_policy
  get '/store/sales-tax' => 'products#sales_tax', :as => :sales_tax
  get '/store/new-arrivals' => 'products#new_arrivals', :as => :new_arrivals
  get '/store/sale-items' => 'products#sale_items', :as => :sale_items

  resources :boxes, path: '/store/boxes'
  resources :shipments, path: '/store/shipments'
  resources :addresses, path: '/store/users/addresses'
  resource :cart, only: [:show], path: '/store/cart'
  resource :checkout, path: '/store/checkout'
  resources :items, path: '/store/items'
  resources :orders, path: '/store/orders'
  devise_for :users, path: '/store/users', controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  resources :users, path: '/store/users', only: [:show, :index, :destroy]
  resources :photos, path: '/store/photos'
  resources :products, path: '/store'
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]

  root 'showcase#home'
  get '/alchemist-series/avani.odt' => 'showcase#download_avani', :as => :avani
  get '/alchemist-series/ember.odt' => 'showcase#download_ember', :as => :ember
  get '/alchemist-series/zephyr.odt' => 'showcase#download_zephyr', :as => :zephyr
  get '/alchemist-series' => 'showcase#alchemist_series', :as => :alchemist_series
  get '/about' => 'showcase#about', :as => :about
  get '/boddington-rifle-project' => 'showcase#boddington_rifle_project', :as => :boddington_rifle_project
  get '/bracelet-helpers' => 'showcase#bracelet_helpers', :as => :bracelet_helpers
  get '/contact' => 'showcase#contact', :as => :contact
  get '/custom-rifles' => 'showcase#custom_rifles', :as => :custom_rifles
  get '/engraving' => 'showcase#engraving', :as => :engraving
  get '/events' => 'showcase#events', :as => :events
  get '/finishes' => 'showcase#finishes', :as => :finishes
  get '/gun-fitting' => 'showcase#gun_fitting', :as => :gun_fitting
  get '/gun-parts' => 'showcase#gun_parts', :as => :gun_parts
  get '/guns-for-sale' => 'showcase#guns_for_sale', :as => :guns_for_sale
  get '/gunsmithing' => 'showcase#gunsmithing', :as => :gunsmithing
  get '/home' => 'showcase#home', :as => :home
  get '/key-chains' => 'showcase#key_chains', :as => :key_chains
  get '/leather-wrap-pads' => 'showcase#leather_wrap_pads', :as => :leather_wrap_pads
  get '/media' => 'showcase#media', :as => :media
  get '/payment-and-shipping' => 'showcase#payment_and_shipping', :as => :payment_and_shipping
  get '/pistols' => 'showcase#pistols', :as => :pistols
  get '/pens' => 'showcase#pens', :as => :pens
  get '/restoration' => 'showcase#restoration', :as => :restoration
  get '/shotguns' => 'showcase#shotguns', :as => :shotguns
  get '/stock-work' => 'showcase#stock_work', :as => :stock_work
  get '/synthetic-rifles' => 'showcase#synthetic_rifles', :as => :synthetic_rifles
  get '/taylors-pens-and-gifts' => 'showcase#taylors_pens_and_gifts', :as => :taylors_pens_and_gifts
  get '/trophy-room' => 'showcase#trophy_room', :as => :trophy_room
  get '/wine-stoppers' => 'showcase#wine_stoppers', :as => :wine_stoppers

end

app/models/box.rb
class Box < ActiveRecord::Base
  before_validation :default_values

  def default_values
    self.provider = provider.strip.downcase
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :index]
  layout 'store'
  # GET /boxes
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  def create
    @box = Box.new(box_params)

    if @box.save
      redirect_to @box, notice: 'Box was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /boxes/1
  def update
    if @box.update(box_params)
      redirect_to @box, notice: 'Box was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /boxes/1
  def destroy
    @box.destroy
    redirect_to boxes_url, notice: 'Box was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_box
    @box = Box.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def box_params
    params.require(:box).permit(:provider, :length, :height, :width, :weight)
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.haml
= form_for @box do |f|
  - if @box.errors.any?
    #error_explanation
      %h2= "#{pluralize(@box.errors.count, "error")} prohibited this box from being saved:"
      %ul
        - @box.errors.full_messages.each do |msg|
          %li= msg

  .field
    .input-group
      %span#provider-addon.input-group-addon Provider
      = f.text_field :provider, placeholder: "Provider", class: "form-control input-lg","aria-describedby" => "provider-addon"
  .field
    .input-group
      %span#length-addon.input-group-addon Length
      = f.number_field :length, :class => 'text_field', :step => 0.1, placeholder: "5 cm", class: "form-control input-lg","aria-describedby" => "length-addon"
  .field
    .input-group
      %span#height-addon.input-group-addon Height
      = f.number_field :height, :class => 'text_field', :step => 0.1, placeholder: "2 cm", class: "form-control input-lg","aria-describedby" => "height-addon"
  .field
    .input-group
      %span#width-addon.input-group-addon Width
      = f.number_field :width, :class => 'text_field', :step => 0.1, placeholder: "3 cm", class: "form-control input-lg","aria-describedby" => "width-addon"
  .field
    .input-group
      %span#weight-addon.input-group-addon Weight
      = f.number_field :weight, :class => 'text_field', :step => 0.001, placeholder: "1000 g", class: "form-control input-lg","aria-describedby" => "weight-addon"
  %p
  .actions
    = f.submit 'Save', :class => "btn btn-primary"
%p

app/views/boxes/edit.html.haml
%h1 Editing box

= render 'form'

= link_to 'Show', @box, :class => "btn btn-primary"
\|
= link_to 'Back', boxes_path, :class => "btn btn-primary"

app/views/boxes/index.html.haml
- content_for :title,  "Boxes"
.page-header
  %h1 Boxes
= link_to 'New Box', new_box_path, :class => "btn btn-primary"
%br
%table.table.table-hover
  %thead
    %tr
      %th Proivder
      %th Length
      %th Height
      %th Width
      %th Weight
      %th
  %tbody
    - @boxes.each do |box|
      %tr
        %td= box.provider
        %td= box.length
        %td= box.height
        %td= box.width
        %td= box.weight
        %td
          = link_to 'Show', box, :class => "btn btn-primary btn-block"
          = link_to 'Edit', edit_box_path(box), :class => "btn btn-primary btn-block"
          = link_to 'Destroy', box, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger btn-block"

app/views/boxes/new.html.haml
%h1 New box

= render 'form'

= link_to 'Back', boxes_path, :class => "btn btn-primary"

app/views/boxes/show.html.haml
%p#notice= notice

%p
  %b Provider:
  = @box.provider
%p
  %b Length:
  = @box.length
%p
  %b Height:
  = @box.height
%p
  %b Width:
  = @box.width
%p
  %b Weight:
  = @box.weight

= link_to 'Edit', edit_box_path(@box), :class => "btn btn-primary"
\|
= link_to 'Back', boxes_path, :class => "btn btn-primary"