config/routes.rb
Rails.application.routes.draw do

  resources :tiles, path: '/store/tiles'
  resources :shippers, path: '/store/shippers'
  resources :authentications
  get '/store/orders/carts' => 'orders#carts', :as => :carts
  get '/store/orders/details/:id' => 'orders#details', :as => :order_details
  get '/store/orders/invoice/:id' => 'orders#invoice', :as => :order_invoice
  get '/store/orders/invoice/:id/print' => 'orders#print', :as => :order_print
  get '/store/checkout/address-select' => 'checkouts#address_select', :as => :address_select
  get '/store/checkout/shipping-select' => 'checkouts#shipping_select', :as => :shipping_select
  get '/store/checkout/review' => 'checkouts#review', :as => :review
  get '/store/checkout/process-order' => 'checkouts#process_order', :as => :process_order
  get '/store/checkout/packaging' => 'checkouts#packaging', :as => :packaging
  get '/approved', to: redirect('approved.html'), :as => :approved_js
  get '/disapproved', to: redirect('disapproved.html'), :as => :disapproved_js
  get '/store/checkout/approved' => 'checkouts#approved', :as => :approved
  get '/store/checkout/disapproved' => 'checkouts#disapproved', :as => :disapproved
  post '/store/checkout/approved' => 'checkouts#approved_post', :as => :approved_post
  post '/store/checkout/disapproved' => 'checkouts#disapproved_post', :as => :disapproved_post
  get '/store/main' => 'products#main', :as => :store_main
  get '/store/products' => 'products#products', :as => :product_management
  get '/store/gun-parts' => 'products#gun_parts', :as => :gunparts
  get '/store/custom-parts' => 'products#custom_parts', :as => :custom_parts
  get '/store/wood' => 'products#wood', :as => :wood
  get '/store/barrels' => 'products#barrels', :as => :barrels
  get '/store/optics' => 'products#optics', :as => :optics
  get '/store/gifts' => 'products#gifts', :as => :gifts
  get '/store/jewlery' => 'products#jewelry', :as => :jewelry
  get '/store/decor' => 'products#decor', :as => :decor
  get '/store/gun-cases' => 'products#gun_cases', :as => :gun_cases
  get '/store/guns' => 'products#guns', :as => :guns
  get '/store/contact' => 'products#contact', :as => :store_contact
  get '/store/privacy-policy' => 'products#privacy_policy', :as => :privacy_policy
  get '/store/return-policy' => 'products#return_policy', :as => :return_policy
  get '/store/terms-and-conditions' => 'products#terms_and_conditions', :as => :terms_and_conditions
  get '/store/payment-policy' => 'products#payment_policy', :as => :payment_policy
  get '/store/shipping-policy' => 'products#shipping_policy', :as => :shipping_policy
  get '/store/sales-tax' => 'products#sales_tax', :as => :sales_tax
  get '/store/new-arrivals' => 'products#new_arrivals', :as => :new_arrivals
  get '/store/sale-items' => 'products#sale_items', :as => :sale_items

  resources :boxes, path: '/store/boxes'
  resources :shipments, path: '/store/shipments'
  resources :addresses, path: '/store/users/addresses'
  resource :cart, only: [:show], path: '/store/cart'
  resource :checkout, path: '/store/checkout'
  resources :items, path: '/store/items'
  resources :orders, path: '/store/orders'
  devise_for :users, path: '/store/users', controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  resources :users, path: '/store/users', only: [:show, :index, :destroy]
  resources :photos, path: '/store/photos'
  resources :products, path: '/store'
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]

  root 'showcase#home'
  get '/alchemist-series/avani.odt' => 'showcase#download_avani', :as => :avani
  get '/alchemist-series/ember.odt' => 'showcase#download_ember', :as => :ember
  get '/alchemist-series/zephyr.odt' => 'showcase#download_zephyr', :as => :zephyr
  get '/alchemist-series' => 'showcase#alchemist_series', :as => :alchemist_series
  get '/about' => 'showcase#about', :as => :about
  get '/boddington-rifle-project' => 'showcase#boddington_rifle_project', :as => :boddington_rifle_project
  get '/bracelet-helpers' => 'showcase#bracelet_helpers', :as => :bracelet_helpers
  get '/contact' => 'showcase#contact', :as => :contact
  get '/custom-rifles' => 'showcase#custom_rifles', :as => :custom_rifles
  get '/engraving' => 'showcase#engraving', :as => :engraving
  get '/events' => 'showcase#events', :as => :events
  get '/finishes' => 'showcase#finishes', :as => :finishes
  get '/gun-fitting' => 'showcase#gun_fitting', :as => :gun_fitting
  get '/gun-parts' => 'showcase#gun_parts', :as => :gun_parts
  get '/guns-for-sale' => 'showcase#guns_for_sale', :as => :guns_for_sale
  get '/gunsmithing' => 'showcase#gunsmithing', :as => :gunsmithing
  get '/home' => 'showcase#home', :as => :home
  get '/key-chains' => 'showcase#key_chains', :as => :key_chains
  get '/leather-wrap-pads' => 'showcase#leather_wrap_pads', :as => :leather_wrap_pads
  get '/media' => 'showcase#media', :as => :media
  get '/payment-and-shipping' => 'showcase#payment_and_shipping', :as => :payment_and_shipping
  get '/pistols' => 'showcase#pistols', :as => :pistols
  get '/pens' => 'showcase#pens', :as => :pens
  get '/restoration' => 'showcase#restoration', :as => :restoration
  get '/shotguns' => 'showcase#shotguns', :as => :shotguns
  get '/stock-work' => 'showcase#stock_work', :as => :stock_work
  get '/synthetic-rifles' => 'showcase#synthetic_rifles', :as => :synthetic_rifles
  get '/taylors-pens-and-gifts' => 'showcase#taylors_pens_and_gifts', :as => :taylors_pens_and_gifts
  get '/trophy-room' => 'showcase#trophy_room', :as => :trophy_room
  get '/wine-stoppers' => 'showcase#wine_stoppers', :as => :wine_stoppers

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  layout 'store'

  def address_select
    @addresses = Address.where(user_id: current_user.id)
    @address = Address.new
    @order = current_order
    @order.phase = 2
    @order.save!
  end

  def shipping_select
    current_order.update_items
    @order = current_order
    if @order.phase == 2
      @order.phase = 3
      @order.save!
    else
      redirect_to address_select_path
    end
    @shipping_methods = @order.shipping_methods
    product_ids = @order.items.map(&:product_id)
    @shippers = Shipper.where(id: Product.where(id: product_ids).uniq.pluck(:shipper_id).sort_by { |i| [i ? 1 : 0, i] })
    @shippers.count.times { @order.shipping_methods.build }
    @packed = []
    @rates = []
    destination = make_active_location(@order.get_address)
    destination_ups = make_active_location_ups(@order.get_address)

    @shippers.each do |shipper|
      origin = make_active_location(shipper.address)
      origin_ups = make_active_location_ups(shipper.address)
      if shipper.scheme == 0
        pack = []
        rate = []
        @items = @order.items.joins(:product).where(products: { shipper_id: shipper.id })
        if @items.count > 0

          if shipper.usps
            usps_packed = make_packages('usps', @items)
            pack.push((usps_packed.include? nil) ? [] : usps_packed)
            if !usps_packed.include? nil
              usps_packages = make_active_packages(usps_packed)
              rate.push(usps_rates(origin, destination, usps_packages))
            end
          end

          if shipper.fedex
            fedex_packed = make_packages('fedex', @items)
            pack.push((fedex_packed.include? nil) ? [] : fedex_packed)
            if !fedex_packed.include? nil
              fedex_packages = make_active_packages(fedex_packed)
              rate.push(fedex_rates(origin, destination, fedex_packages))
            end
          end

          if shipper.ups
            ups_packed = make_packages('ups', @items)
            pack.push((ups_packed.include? nil) ? [] : ups_packed)
            if !ups_packed.include? nil
              ups_packages = make_active_packages(ups_packed)
              rate.push(ups_rates(origin_ups, destination_ups, ups_packages))
            end
          end

        end
        @rates.push(rate)
        @packed.push(pack)
      end
    end
    @shipping_information = @shippers.zip(@order.shipping_methods, @packed, @rates)
    Rails.cache.delete(:shipping_information)
    Rails.cache.write(:shipping_information, @shippers.zip(@packed))
  end

  def review
    @order = current_order
    if @order.phase != 4
      redirect_to address_select_path
    end
  end

  def process_order
    @order = current_order
    @shipping_methods = @order.shipping_methods
    if @shipping_methods.count > 0
      @order.shipments.destroy_all
      @order.shipments = []
      @shipping_information = Rails.cache.read(:shipping_information)
      i = 0
      @shipping_information.each do |shipper, packed|
        if shipper.scheme == 0
          if @shipping_methods[i].service_name.downcase.include? 'fedex'
            make_shipments(@order, shipper, packed.find {|p| !p.empty? && p.first.label == 'fedex'}).each { |shipment| @order.shipments.push(shipment) }
          elsif @shipping_methods[i].service_name.downcase.include? 'usps'
            make_shipments(@order, shipper, packed.find {|p| !p.empty? && p.first.label == 'usps'}).each { |shipment| @order.shipments.push(shipment) }
          elsif @shipping_methods[i].service_name.downcase.include? 'ups'
            make_shipments(@order, shipper, packed.find {|p| !p.empty? && p.first.label == 'ups'}).each { |shipment| @order.shipments.push(shipment) }
          end
        elsif shipper.scheme == 1
          @order.shipments.push(make_pack_shipment(@order, shipper))
        elsif shipper.scheme == 2
          @order.shipments.push(make_pack_shipment(@order, shipper))
        end
        i += 1
      end
      @order.shipping = @order.shipping_methods.sum(:price)
      st = @order.get_address.state.to_s.downcase
      if st == 'texas' || st == 'tx' || st == 'lone star state' || st == 'beef state' || st == 'jumbo state' || st == 'super-american state' || st == 'banner state' || st == 'blizzard state'
        @order.tax = ('%.2f' % ((@order.subtotal + @order.shipping).to_f * 0.0675))
      else
        @order.tax = 0.0
      end
      @order.ordered_on = DateTime.now
      @order.phase = 4
      @order.save!
      @order.update_order
    end
    redirect_to review_path
  end

  def packaging
    @order = current_order
    @order.phase = 5
    @order.save!
  end

  def approved_post
    redirect_to approved_js_url
  end

  def approved
    @order = current_order
    if @order.phase == 5
      @order.phase = 6
      @order.save!
      if @order.items.count > 0
        @order.items.each do |item|
          item.product.quantity -= item.quantity
          item.product.save
        end
        current_user.create_cart
      end
    end

  end

  def disapproved_post
    redirect_to disapproved_js_url
  end

  def disapproved
  end

  private

  def make_pack_shipment(order, shipper)
    shipment = Shipment.new(order_id: order.id, shipped_by: shipper.company_name)
    items = order.items.joins(:product).where(products: { shipper_id: shipper.id })
    items.each do |item|
      shipment.units.new(product_id: item.product.id,
                         quantity: item.quantity,
                         price: item.product.get_price)
    end
    shipment
  end

  def make_shipments(order, shipper, packed)
    shipments = []
    packed.each do |entry|
      shipments.push(make_shipment(order, shipper, entry))
    end
    shipments
  end

  def make_shipment(order, shipper, packed)
    shipment = Shipment.new(order_id: order.id, shipped_by: shipper.company_name)
    counts = Hash.new(0)
    packed.packings.first.each { |entry| counts[entry.label] += 1 }
    counts.each do |entry|
      product = Product.where(url: entry.first).first
      shipment.units.new(product_id: product.id,
                         quantity: entry.last,
                         price: product.get_price)
    end
    shipment
  end

  def make_active_packages(packed)
    packages = []
    packed.each do |pack|
      packages.push(make_active_package(pack))
    end
    packages
  end

  def make_active_package(pack) # 1.15 is to give a 15% buffer weight
    products = [];
    pack.packings.first.each {|e| products.push(e.label)}
    insurance = Product.where(:url => products).sum(:price)
    ActiveShipping::Package.new((pack.weight_limit - pack.packings.first.remaining_weight) * 1.15, [pack.dimensions.x, pack.dimensions.y, pack.dimensions.z], value: insurance, currency: 'USD', insurance_price: insurance, insured_price: insurance)
  end

  def make_active_location(address)
    ActiveShipping::Location.new(name: address.prefix.to_s + ' ' + address.first_name.to_s + ' ' + address.middle_name.to_s + address.last_name.to_s + ' ' + address.suffix.to_s,
                                 address1: address.address_line1,
                                 address2: address.address_line2,
                                 phone: address.phone,
                                 country: address.country,
                                 state: address.state,
                                 city: address.city,
                                 zip: address.zip)
  end

  def make_active_location_ups(address)
    ActiveShipping::Location.new(name: address.prefix.to_s + ' ' + address.first_name.to_s + ' ' + address.middle_name.to_s + address.last_name.to_s + ' ' + address.suffix.to_s,
                                 address1: address.address_line1,
                                 address2: address.address_line2,
                                 phone: address.phone,
                                 country: address.country,
                                 city: address.city,
                                 zip: address.zip)
  end

  def make_packages(provider, items)
    individual = items.joins(:product).where(products: { exclusive: true, has_box: false })
    grouped = items.joins(:product).where(products: { exclusive: false, has_box: false })
    selfpacked = items.joins(:product).where(products: { has_box: true })
    packages = []
    individual.each do |item|
      entry = best_fit(provider, [item])
      packages.push(entry)
    end

    while grouped.count > 0
      entry = best_fit(provider, grouped)
      packages.push(entry)
      grouped = remove_from(entry, grouped)
    end

    selfpacked.each do |spack|
      packages.push(spackup(provider, spack))
    end
    packages
  end


  def spackup(provider, item)
    BoxPacker.container [item.product.shipping_width, item.product.shipping_height, item.product.shipping_length], label: provider, weight_limit: item.product.shipping_weight do
      add_item [item.product.shipping_width, item.product.shipping_height, item.product.shipping_length], label: item.product.url, weight: item.product.shipping_weight, quantity: item.quantity
      pack!
    end
  end


  def remove_from(entry, items)
    items_list = items.dup
    if entry
      entry.packings.first.each do |package|
        if items_list.each do |item|
             item.quantity -= 1 if item.product.url == package.label
           end
        end
      end
      items_list.reject { |x| x.quantity == 0 }
    else
      []
    end
  end

  def best_fit(provider, items)
    entries = []
    Box.where(provider: provider).each do |box|
      entries.push(packup(box, items))
    end
    entries.delete_if { |x| x.packings.count == 0 }
    entries = entries.sort_by { |obj| [obj.packings.count, obj.packings.first.remaining_volume] }
    if entries.count > 0
      if entries.first.packings.count > 1
        entries.first.packings.pop(entries.first.packings.count - 1)
      end
    end
    entries.first
  end

  def packup(box, items)

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/address_select.html.haml
- content_for :title,  "Select shipping address"
.page-header
  %h1 Select a shipping address
-@order.update_order
.panel-panel-default
  .panel-body
    - @addresses.each do |address|
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        -if !address.first_name.nil? && !address.first_name.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              %b=address.name
        -if !address.address_line1.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.address_line1.titleize
        -if !address.address_line2.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.address_line2.titleize
        -if !address.city.empty? && !address.state.empty? && !address.zip.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12
              =(address.city.to_s + ', ' + address.state.to_s + ' ' + address.zip.to_s).titleize
        -if !address.country.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12=ISO3166::Country[address.country]
        -if !address.phone.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12= "Phone: " + address.phone.to_s 
        -if !address.fax.nil? && !address.fax.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12= "Fax: " + address.fax.to_s
        -if !address.company.nil? && !address.company.empty?
          .row
            .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.company.to_s.titleize
        .row
          .btn-group-verticle{ :style => "width:80%;" }
            = form_for @order do |f|
              .field= f.hidden_field :address_id, value: address.id
              .action= f.submit 'Ship to this address', :class => "btn btn-primary", style: "width:100%;"
            .btn-group{ :style => "width:100%;" }
              = link_to 'Edit', edit_address_path(:id => address.id, :address_select => true), class: "btn btn-primary", style: "width:50%;"
              = link_to 'Delete', address_path(:id => address.id, :address_select => true), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger", style: "width:50%;"
        %p
%h2 Add new address

= render '/addresses/address_select_form'
%br
%br

app/views/checkouts/approved.html.haml
- content_for :title,  "Approved"
.page-header
  %h1 Your order has been proccessed

%p
  ="You can view information about your order under "
  =link_to 'Orders', orders_path

%p
  Thank you for shopping

app/views/checkouts/disapproved.html.haml
- content_for :title,  "Disapproved"
.page-header
  %h1 Your order has failed to be proccessed

%p
  Due to payment and billing failure, we are unable to complete your order.

%p
  Thank you for shopping

app/views/checkouts/packaging.html.haml
- content_for :title,  "Packaging"
.page-header
  %h1 Packaging
:css
  .loader {
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    border-bottom: 16px solid #3498db;
    width: 120px;
    height: 120px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
  }

  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  .centered{
    width: 100%;
    display: flex;
    justify-content: center;
  }

.centered
  .loader{}


%form{:action => "https://www.eprocessingnetwork.com/cgi-bin/dbe/order.pl",:id => 'form', :method => "POST"}
  =hidden_field_tag 'ePNAccount', ENV['EPNACCOUNT']
  =hidden_field_tag 'LogoURL', "https://customgun.com/assets/theme/default/tr.png"
  %input{:name => "Redirect", :type => "HIDDEN", :value => "1"}/
  =hidden_field_tag 'ReturnApprovedURL', approved_post_url
  =hidden_field_tag 'ReturnDeclinedURL', disapproved_post_url
  =hidden_field_tag 'TaxRate', '0.0675'
  %input{:name => "ApplyTax", :type => "checkbox", :checked => "#{@order.tax != 0.0 ? "check" : ""}", :style => "display: none;"}
  =hidden_field_tag 'BillFirstName', @order.get_address.first_name
  =hidden_field_tag 'BillLastName', @order.get_address.last_name
  =hidden_field_tag 'BillAddress', @order.get_address.address_line1
  =hidden_field_tag 'BillCity', @order.get_address.city.titleize
  =hidden_field_tag 'BillState', @order.get_address.state_code
  =hidden_field_tag 'BillCountry', ISO3166::Country[@order.get_address.country]
  =hidden_field_tag 'BillZip', @order.get_address.zip
  =hidden_field_tag 'BillPhone', @order.get_address.phone
  =hidden_field_tag 'BillEMail', current_user.email
  =hidden_field_tag 'FirstName', @order.get_address.first_name.titleize
  =hidden_field_tag 'LastName', @order.get_address.last_name.titleize
  =hidden_field_tag 'Address', (@order.get_address.address_line1.nil? ? @order.get_address.address_line2.titleize : @order.get_address.address_line1.titleize)
  =hidden_field_tag 'City', @order.get_address.city.titleize
  =hidden_field_tag 'State', @order.get_address.state_code
  =hidden_field_tag 'Country', ISO3166::Country[@order.get_address.country]
  =hidden_field_tag 'Zip', @order.get_address.zip
  =hidden_field_tag 'Company', @order.get_address.company.titleize
  =hidden_field_tag 'Phone', @order.get_address.phone
  =hidden_field_tag 'EMail', current_user.email
  -@order.items.each do |item|
    =hidden_field_tag 'ItemQty', item.quantity
    =hidden_field_tag 'ItemCost', item.price
    =hidden_field_tag 'ItemDesc', item.product.title.titleize
  =hidden_field_tag 'Total' , @order.total
  =submit_tag "",  :style => "display: none;"

:javascript
  window.onload = function(){
  document.getElementById('form').submit();
  }

app/views/checkouts/review.html.haml
- content_for :title,  "Review your order"
.page-header
  %h1 Review your order
=form_for @order do |f|
  .row
    .col-lg-8.col-md-8.col-sm-8.col-xs-12
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          .panel.panel-default
            .panel-body
              %b Shipping Address
              -address = @order.get_address
              .row
                .col-lg-12.col-md-12.col-sm-12.col-xs-12
                  -if !address.first_name.nil? && !address.first_name.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12= address.name
                  -if !address.address_line1.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.address_line1.titleize
                  -if !address.address_line2.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.address_line2.titleize
                  -if !address.city.empty? && !address.state.empty? && !address.zip.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12
                        =(address.city.to_s + ', ' + address.state.to_s + ' ' + address.zip.to_s).titleize
                  -if !address.country.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12=ISO3166::Country[address.country]
                  -if !address.phone.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12= "Phone: " + address.phone.to_s
                  -if !address.fax.nil? && !address.fax.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12= "Fax: " + address.fax.to_s
                  -if !address.company.nil? && !address.company.empty?
                    .row
                      .col-lg-12.col-md-12.col-sm-12.col-xs-12=address.company.to_s.titleize
                    %p
                    %p
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          .panel.panel-default
            .panel-body
              .row
                .col-lg-12
                  %b
                    Comment
                  %p
                  .field= f.text_area :comment, class: 'form-control input'
              %p
              -@order.items.each do |unit|
                .row
                  .col-lg-4
                    .widewrapper=image_tag(unit.product.photos.first.image.thumb) unless unit.product.photos.first.nil?
                  .col-lg-8
                    %h4
                      %b
                        =unit.product.title.titleize
                    %p
                      .text-danger
                        %b
                          = "Price #{number_to_currency unit.price}"
                    %p
                    %b
                      = "Quantity #{unit.quantity}"
                %p


    .col-lg-4.col-md-4.col-sm-4.col-xs-12
      .row
        .col-lg-12.col-md-12.col-sm-12.col-xs-12
          .panel.panel-default
            .panel-body
              .row
                .col-lg-12
                  .action
                    =f.submit 'Continue', name: "packaging", class: 'btn btn-primary btn-block'
                  %p
                  %p
                    By placing your order, you agree to customgun.com's
                    = link_to('payment policy', payment_policy_path, :target => '_blank') + ', '
                    = link_to('privacy policy', privacy_policy_path, :target => '_blank') + ', '
                    = link_to('return policy', return_policy_path, :target => '_blank') + ', and '
                    = link_to('shipping policy', shipping_policy_path, :target => '_blank') + '.'
              .row
                .col-lg-12
                  %b Order Summary
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  ="Items (#{@order.quantity}):"
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .pull-right= number_to_currency @order.cost
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  Shipping & handling:
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .pull-right= number_to_currency @order.shipping_and_handling
              %hr
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  Total before tax:
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .pull-right= number_to_currency @order.total_before_tax
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  Tax to be collected:
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .pull-right= number_to_currency @order.tax
              %hr
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .text-danger
                    %b Order Total:
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .pull-right
                    .text-danger
                      %b= number_to_currency @order.total

app/views/checkouts/shipping_select.html.haml
- content_for :title,  "Select shipping options"
.page-header
  %h1 Choose your shipping options
=form_for @order do |f|
  .row
    .pull-right
      .action
        = f.submit 'Continue', name: "process_order", :class => "btn btn-primary"
  -@shipping_information.each do |shipper, shipping_method, packed, rates|
    .row
      .col-md-6.col-sm-6.col-xs-6
        .row
          %h4= "Shipping from #{shipper.company_name unless shipper.nil?}"
        .row= "Shipping to #{@order.get_address.display}"
        %p
        -@order.items.joins(:product).where(products: {shipper_id: shipper.id}).each do |item|
          -if !item.product_id.nil?
            -product = Product.find(item.product_id)
            .row
              %ul
                %li
                  %b= product.title.titleize
                  %p
                    = "Price #{number_to_currency item.price} - Quantity: #{item.quantity}"
              %p
      .col-md-6.col-sm-6.col-xs-6
        %h3 Choose a delivery option
        =f.fields_for :shipping_methods, shipping_method do |ff|
          -if shipper.scheme == 0
            -if rates
              - rates.flatten!(1)
              - rates.each_with_index do |s, i|
                - price =s.price.to_f / 100 + shipper.handling_fee.to_f + s.price.to_f / 100 * shipper.up_charge_rate.to_f
                .field
                  -if i == 0
                    = ff.radio_button :price, [price,:service_name => s.service_name], :checked => true
                  -else
                    = ff.radio_button :price,[price,:service_name => s.service_name], :checked => false
                  = "#{number_to_currency(price)} - #{s.service_name}"
          -elsif shipper.scheme == 1
            - price = shipper.price.to_f + shipper.handling_fee.to_f
            -if shipper.usps
              .field
                = ff.radio_button :price, [price,:service_name => 'USPS Flat Rate'], :checked => true
                = "#{number_to_currency(price)} - USPS Flat Rate"
            -if shipper.fedex
              .field
                = ff.radio_button :price, [price,:service_name => 'Fedex Flat Rate'], :checked => true
                = "#{number_to_currency(price)} - Fedex Flat Rate"
            -if shipper.ups
              .field
                = ff.radio_button :price, [price,:service_name => 'UPS Flat Rate'], :checked => true
                = "#{number_to_currency(price)} - UPS Flat Rate"
          -elsif shipper.scheme == 2
            .field
              - price = shipper.price.to_f + shipper.handling_fee.to_f
              = ff.radio_button :price, [price,:service_name => 'Digital Download'], :checked => true
              = "#{number_to_currency(price)} - Digital Download"
  .row
    .pull-right
      .action
        = f.submit 'Continue', name: "process_order", :class => "btn btn-primary"