config/routes.rb
Rails.application.routes.draw do

  resources :tiles, path: '/store/tiles'
  resources :shippers, path: '/store/shippers'
  resources :authentications
  get '/store/orders/carts' => 'orders#carts', :as => :carts
  get '/store/orders/details/:id' => 'orders#details', :as => :order_details
  get '/store/orders/invoice/:id' => 'orders#invoice', :as => :order_invoice
  get '/store/orders/invoice/:id/print' => 'orders#print', :as => :order_print
  get '/store/checkout/address-select' => 'checkouts#address_select', :as => :address_select
  get '/store/checkout/shipping-select' => 'checkouts#shipping_select', :as => :shipping_select
  get '/store/checkout/review' => 'checkouts#review', :as => :review
  get '/store/checkout/process-order' => 'checkouts#process_order', :as => :process_order
  get '/store/checkout/packaging' => 'checkouts#packaging', :as => :packaging
  get '/approved', to: redirect('approved.html'), :as => :approved_js
  get '/disapproved', to: redirect('disapproved.html'), :as => :disapproved_js
  get '/store/checkout/approved' => 'checkouts#approved', :as => :approved
  get '/store/checkout/disapproved' => 'checkouts#disapproved', :as => :disapproved
  post '/store/checkout/approved' => 'checkouts#approved_post', :as => :approved_post
  post '/store/checkout/disapproved' => 'checkouts#disapproved_post', :as => :disapproved_post
  get '/store/main' => 'products#main', :as => :store_main
  get '/store/products' => 'products#products', :as => :product_management
  get '/store/gun-parts' => 'products#gun_parts', :as => :gunparts
  get '/store/custom-parts' => 'products#custom_parts', :as => :custom_parts
  get '/store/wood' => 'products#wood', :as => :wood
  get '/store/barrels' => 'products#barrels', :as => :barrels
  get '/store/optics' => 'products#optics', :as => :optics
  get '/store/gifts' => 'products#gifts', :as => :gifts
  get '/store/jewlery' => 'products#jewelry', :as => :jewelry
  get '/store/decor' => 'products#decor', :as => :decor
  get '/store/gun-cases' => 'products#gun_cases', :as => :gun_cases
  get '/store/guns' => 'products#guns', :as => :guns
  get '/store/contact' => 'products#contact', :as => :store_contact
  get '/store/privacy-policy' => 'products#privacy_policy', :as => :privacy_policy
  get '/store/return-policy' => 'products#return_policy', :as => :return_policy
  get '/store/terms-and-conditions' => 'products#terms_and_conditions', :as => :terms_and_conditions
  get '/store/payment-policy' => 'products#payment_policy', :as => :payment_policy
  get '/store/shipping-policy' => 'products#shipping_policy', :as => :shipping_policy
  get '/store/sales-tax' => 'products#sales_tax', :as => :sales_tax
  get '/store/new-arrivals' => 'products#new_arrivals', :as => :new_arrivals
  get '/store/sale-items' => 'products#sale_items', :as => :sale_items

  resources :boxes, path: '/store/boxes'
  resources :shipments, path: '/store/shipments'
  resources :addresses, path: '/store/users/addresses'
  resource :cart, only: [:show], path: '/store/cart'
  resource :checkout, path: '/store/checkout'
  resources :items, path: '/store/items'
  resources :orders, path: '/store/orders'
  devise_for :users, path: '/store/users', controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  resources :users, path: '/store/users', only: [:show, :index, :destroy]
  resources :photos, path: '/store/photos'
  resources :products, path: '/store'
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]

  root 'showcase#home'
  get '/alchemist-series/avani.odt' => 'showcase#download_avani', :as => :avani
  get '/alchemist-series/ember.odt' => 'showcase#download_ember', :as => :ember
  get '/alchemist-series/zephyr.odt' => 'showcase#download_zephyr', :as => :zephyr
  get '/alchemist-series' => 'showcase#alchemist_series', :as => :alchemist_series
  get '/about' => 'showcase#about', :as => :about
  get '/boddington-rifle-project' => 'showcase#boddington_rifle_project', :as => :boddington_rifle_project
  get '/bracelet-helpers' => 'showcase#bracelet_helpers', :as => :bracelet_helpers
  get '/contact' => 'showcase#contact', :as => :contact
  get '/custom-rifles' => 'showcase#custom_rifles', :as => :custom_rifles
  get '/engraving' => 'showcase#engraving', :as => :engraving
  get '/events' => 'showcase#events', :as => :events
  get '/finishes' => 'showcase#finishes', :as => :finishes
  get '/gun-fitting' => 'showcase#gun_fitting', :as => :gun_fitting
  get '/gun-parts' => 'showcase#gun_parts', :as => :gun_parts
  get '/guns-for-sale' => 'showcase#guns_for_sale', :as => :guns_for_sale
  get '/gunsmithing' => 'showcase#gunsmithing', :as => :gunsmithing
  get '/home' => 'showcase#home', :as => :home
  get '/key-chains' => 'showcase#key_chains', :as => :key_chains
  get '/leather-wrap-pads' => 'showcase#leather_wrap_pads', :as => :leather_wrap_pads
  get '/media' => 'showcase#media', :as => :media
  get '/payment-and-shipping' => 'showcase#payment_and_shipping', :as => :payment_and_shipping
  get '/pistols' => 'showcase#pistols', :as => :pistols
  get '/pens' => 'showcase#pens', :as => :pens
  get '/restoration' => 'showcase#restoration', :as => :restoration
  get '/shotguns' => 'showcase#shotguns', :as => :shotguns
  get '/stock-work' => 'showcase#stock_work', :as => :stock_work
  get '/synthetic-rifles' => 'showcase#synthetic_rifles', :as => :synthetic_rifles
  get '/taylors-pens-and-gifts' => 'showcase#taylors_pens_and_gifts', :as => :taylors_pens_and_gifts
  get '/trophy-room' => 'showcase#trophy_room', :as => :trophy_room
  get '/wine-stoppers' => 'showcase#wine_stoppers', :as => :wine_stoppers

end

app/helpers/application_helper.rb
module ApplicationHelper
  # name: lx
  # description: returns a navigation button for use in the dash
  # usage: lx(image to use, path to link to, text to display)
  def lx(image, path, text)
    link_to(content_tag(:div, image_tag('theme/default/' + image,
                                        alt: t(text),
                                        title: t(text)) + tag(:br) + t(text),
                        class: 'menu_button'), path)
  end

  # name: ptext
  # description: returns text in a p tag, used for paragraphs and normal text
  # usage: ptext('tag_from_yml')
  def ptext(text)
    content_tag(:p, t(text)) + tag(:br)
  end

  def p(text)
    (tag(:br) + content_tag(:p, t(text)) + tag(:br)).html_safe
  end

  # name: qtext
  # description: returns text in a qtext tag, used for quoted text
  # usage: qtext('tag_from_yml')
  def qtext(text)
    tag(:br) + content_tag(:qtext, t(text)) + tag(:br)
  end

  # name: ttext
  # description: returns text in a ttext tag, used for title text
  # usage: ttext('tag_from_yml')
  def ttext(text)
    tag(:br) + content_tag(:ttext, t(text)) + tag(:br)
  end

  # name: itext
  # description: returns text in a itext tag, used under images
  # usage: itext('tag_from_yml')
  def itext(text)
    tag(:br) + content_tag(:itext, t(text)) + tag(:br)
  end

  # name: xtext
  # description: returns text in a xtext tag, used for large text
  # usage: xtext('tag_from_yml')
  def xtext(text)
    tag(:br) + content_tag(:xtext, t(text)) + tag(:br)
  end

  # name: brn
  # description: returns a number of line break tags
  # usage: brn(number of line breaks)
  def brn(number)
    var = ''
    number.times do
      var += tag(:br)
    end
    var.html_safe
  end

  # name: br
  # description: returns a line break tag
  # usage: br()
  def br
    tag(:br)
  end

  # name: gallery
  # description: returns a gallery of images in group
  # usage: gallery(string_list, gallery_name, alt_text)
  # string_list : list of pictures in the format of 'nn1.jpeg nnn.jpeg'
  # gallery_name: gallery id for grouping, example g1
  # alt_text: optional comma seperated alternative in the format of
  # 'text, text1, textn' to skip and entry leave as empty or a blank space
  # as follows 'text1, ,text3,,text5' if there are more images than entries
  # they will be left blank
  def gallery(string_list, gallery_name, alt_text = '')
    gallery_return = ''
    photos = string_list.split(/\ +/)
    photos_text = alt_text.split(',')
    photos.each_with_index do |photo, index|
      gallery_return += link_to(image_tag('thumb/todd_ramirez_' + photo,
                                          alt: photos_text[index],
                                          title: photos_text[index]),
                                'assets/image/todd_ramirez_' + photo,
                                :class => 'image',
                                'data-fancybox-group' => gallery_name)
      gallery_return += '&nbsp;'
    end
    gallery_return.html_safe
  end

  # name: photo
  # description: returns a photo
  # usage: photo(image, alt_text)
  # image: image in the format of 'nnn.jpeg'
  # alt_text: optional alternate text in the format of 'some text'
  def photo(image, alt_text = '')
    image_tag('image/todd_ramirez_' + image,
              alt: alt_text,
              title: alt_text)
  end

  # name: photo_text
  # description: returns a photo with image text
  # usage: photo_text(image, text, alt_text)
  # image: image in the format of 'nnn.jpeg'
  # text: text to display under image use the yml tag 'tag_name'
  # alt_text: optional alternate text in the format of 'some text'
  def photo_text(image, text, alt_text = t(text))
    image_tag('image/todd_ramirez_' + image,
              alt: alt_text,
              title: alt_text) + tag(:br) +
      content_tag(:itext, t(text)) + tag(:br)
  end

  # name: photo_text_s
  # description: returns a photo with image text and 4 line breaks
  # usage: photo_text_s(image, text, alt_text)
  # image: image in the format of 'nnn.jpeg'
  # text: text to display under image use the yml tag 'tag_name'
  # alt_text: optional alternate text in the format of 'some text'
  def photo_text_s(image, text, alt_text = t(text))
    image_tag('image/todd_ramirez_' + image,
              alt: alt_text,
              title: alt_text) + tag(:br) +
      content_tag(:itext, t(text)) + tag(:br) + tag(:br) + tag(:br) + tag(:br)
  end

  # name lightbox_text
  # description: returns a photo in a lightbox, with image text
  # usage: lightbox_text(photo, gallery_name, text, alt_text)
  # photo: image in the format of 'nnn.jpeg'
  # gallery_name: gallery id for grouping, example g1
  # text: text to display under lightbox, use the yml tag 'tag_name'
  # alt_text: optional alternate text in the format of 'some text'
  def lightbox_text(photo, gallery_name, text, alt_text = t(text))
    link_to(image_tag('thumb/todd_ramirez_' + photo,
                      alt: alt_text, title: alt_text),
            'assets/image/todd_ramirez_' + photo,
            :class => 'image', 'data-fancybox-group' => gallery_name) +
      tag(:br) + content_tag(:itext, t(text)) + tag(:br)
  end

  # name lightbox_qtext
  # description: returns a photo in a lightbox, with quoted image text
  # usage: lightbox_qtext(photo, gallery_name, text, alt_text)
  # photo: image in the format of 'nnn.jpeg'
  # gallery_name: gallery id for grouping, example g1
  # text: text to display under lightbox, use the yml tag 'tag_name'
  # alt_text: optional alternate text in the format of 'some text'
  def lightbox_qtext(photo, gallery_name, text, alt_text = t(text))
    link_to(image_tag('thumb/todd_ramirez_' + photo,
                      alt: alt_text, title: alt_text),
            'assets/image/todd_ramirez_' + photo,
            :class => 'image', 'data-fancybox-group' => gallery_name) +
      tag(:br) + content_tag(:qtext, t(text)) + tag(:br)
  end

  # name lightbox
  # description: returns a photo in a lightbox
  # usage: lightbox(photo, gallery_name, alt_text)
  # photo: image in the format of 'nnn.jpeg'
  # gallery_name: gallery id for grouping, example g1
  # alt_text: optional alternate text in the format of 'some text'
  def lightbox(photo, gallery_name, alt_text = '')
    link_to(image_tag('thumb/todd_ramirez_' + photo,
                      alt: alt_text, title: alt_text),
            'assets/image/todd_ramirez_' + photo,
            :class => 'image', 'data-fancybox-group' => gallery_name) +
      tag(:br)
  end

  # name: gallery_text
  # description: returns a gallery of images in group with image text below it
  # usage: gallery_text(string_list, gallery_name, text, alt_text)
  # string_list : list of pictures in the format of 'nn1.jpeg nnn.jpeg'
  # gallery_name: gallery id for grouping, example g1
  # text: text to display under gallery, use the yml tag 'tag_name'
  # alt_text: optional comma seperated alternative in the format of
  # 'text, text1, textn' to skip and entry leave as empty or a blank space
  # as follows 'text1, ,text3,,text5' if there are more images than entries
  # they will be left blank
  def gallery_text(string_list, gallery_name, text, alt_text = '')
    gallery_return = ''
    photos = string_list.split(/\ +/)
    photos_text = alt_text.split(',')
    photos.each_with_index do |photo, index|
      gallery_return += link_to(image_tag('thumb/todd_ramirez_' + photo,
                                          alt: photos_text[index],
                                          title: photos_text[index]),
                                'assets/image/todd_ramirez_' + photo,
                                :class => 'image',
                                'data-fancybox-group' => gallery_name)
      gallery_return += '&nbsp;'
    end
    gallery_return += tag(:br) + content_tag(:itext, t(text)) + tag(:br)
    gallery_return.html_safe
  end
end

app/views/application/_nav.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => store_main_path}=image_tag('theme/store_default/tr.svg', :title => 'Store Home Page', :alt => 'TR', :style => 'height:20px;display:inline;')
    / Collect the nav links, forms, and other content for toggling
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => store_main_path} Store - Home Page
        %li
          %a{:href => home_path} Custom Shop - Home Page
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Departments
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => products_path} All
            %li
              %a{:href => new_arrivals_path} New Arrivals
            %li
              %a{:href => sale_items_path} Sale Items
            %li
              .divider{role: 'separator'}
            - Product.distinct.pluck(:store).sort.map do |c|
              %li
                %a{:href => products_path(department: c)}= c.titleize
            /%li
            /  %a{:href => barrels_path} Barrels
            /%li
            /  %a{:href => custom_parts_path} Custom Parts
            /%li
            /  %a{:href => decor_path} Décor
            /%li
            /  %a{:href => gifts_path} Gifts
            /%li
            /  %a{:href => gun_cases_path} Gun Cases
            /%li
            /  %a{:href => gunparts_path} Gun Parts
            /%li
            /  %a{:href => guns_path} Guns
            /%li
            /  %a{:href => jewelry_path} Jewelry
            /%li
            /  %a{:href => optics_path} Optics
            /%li
            /  %a{:href => wood_path} Wood
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Gunsmithing Services
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => engraving_path} Engraving
            %li
              %a{:href => finishes_path} Finishes
            %li
              %a{:href => gun_fitting_path} Gun Fitting
            %li
              %a{:href => gunsmithing_path} Gun Smithing
            %li
              %a{:href => leather_wrap_pads_path} Leather Wrap Pads
            %li
              %a{:href => pistols_path} Pistols Work
            %li
              %a{:href => restoration_path} Restoration
            %li
              %a{:href => shotguns_path} Shotgun Work
            %li
              %a{:href => stock_work_path} Stock Work


        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Policies & Information
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => store_contact_path} Contact
            %li
              %a{:href => payment_policy_path} Payment Policy
            %li
              %a{:href => privacy_policy_path} Privacy Policy
            %li
              %a{:href => return_policy_path} Return Policy
            %li
              %a{:href => shipping_policy_path} Shipping Policy
            %li
              %a{:href => sales_tax_path} Sales Tax
            %li
              %a{:href => terms_and_conditions_path} Terms and Conditions
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in? && !current_user.guest
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              =icon('fas','user')
              %span.caret
            %ul.dropdown-menu
              %li= link_to current_user.name.titleize, edit_user_registration_path
              %li= link_to "Edit account", edit_user_registration_path
              %li= link_to "Address Book", addresses_path
              %li= link_to 'Authentications', authentications_path
              %li= link_to "Orders", orders_path
              -if current_user.admin?
                %li= link_to "Boxes", boxes_path
                %li= link_to "Carts", carts_path
                %li= link_to "Products", product_management_path
                %li= link_to "Photos", photos_path
                %li= link_to "Shippers", shippers_path
                %li= link_to "Tiles", tiles_path
                %li= link_to "Users", users_path
              %li= link_to "Log out", destroy_user_session_path, :method => :delete
        -else
          %li= link_to "Log in", new_user_session_path
        %li
          %a.navbar-brand{:href => cart_path}
            = icon('fas', 'shopping-cart')
            .badge= current_order.quantity