config/routes.rb
Rails.application.routes.draw do

  resources :tiles, path: '/store/tiles'
  resources :shippers, path: '/store/shippers'
  resources :authentications
  get '/store/orders/carts' => 'orders#carts', :as => :carts
  get '/store/orders/details/:id' => 'orders#details', :as => :order_details
  get '/store/orders/invoice/:id' => 'orders#invoice', :as => :order_invoice
  get '/store/orders/invoice/:id/print' => 'orders#print', :as => :order_print
  get '/store/checkout/address-select' => 'checkouts#address_select', :as => :address_select
  get '/store/checkout/shipping-select' => 'checkouts#shipping_select', :as => :shipping_select
  get '/store/checkout/review' => 'checkouts#review', :as => :review
  get '/store/checkout/process-order' => 'checkouts#process_order', :as => :process_order
  get '/store/checkout/packaging' => 'checkouts#packaging', :as => :packaging
  get '/approved', to: redirect('approved.html'), :as => :approved_js
  get '/disapproved', to: redirect('disapproved.html'), :as => :disapproved_js
  get '/store/checkout/approved' => 'checkouts#approved', :as => :approved
  get '/store/checkout/disapproved' => 'checkouts#disapproved', :as => :disapproved
  post '/store/checkout/approved' => 'checkouts#approved_post', :as => :approved_post
  post '/store/checkout/disapproved' => 'checkouts#disapproved_post', :as => :disapproved_post
  get '/store/main' => 'products#main', :as => :store_main
  get '/store/products' => 'products#products', :as => :product_management
  get '/store/gun-parts' => 'products#gun_parts', :as => :gunparts
  get '/store/custom-parts' => 'products#custom_parts', :as => :custom_parts
  get '/store/wood' => 'products#wood', :as => :wood
  get '/store/barrels' => 'products#barrels', :as => :barrels
  get '/store/optics' => 'products#optics', :as => :optics
  get '/store/gifts' => 'products#gifts', :as => :gifts
  get '/store/jewlery' => 'products#jewelry', :as => :jewelry
  get '/store/decor' => 'products#decor', :as => :decor
  get '/store/gun-cases' => 'products#gun_cases', :as => :gun_cases
  get '/store/guns' => 'products#guns', :as => :guns
  get '/store/contact' => 'products#contact', :as => :store_contact
  get '/store/privacy-policy' => 'products#privacy_policy', :as => :privacy_policy
  get '/store/return-policy' => 'products#return_policy', :as => :return_policy
  get '/store/terms-and-conditions' => 'products#terms_and_conditions', :as => :terms_and_conditions
  get '/store/payment-policy' => 'products#payment_policy', :as => :payment_policy
  get '/store/shipping-policy' => 'products#shipping_policy', :as => :shipping_policy
  get '/store/sales-tax' => 'products#sales_tax', :as => :sales_tax
  get '/store/new-arrivals' => 'products#new_arrivals', :as => :new_arrivals
  get '/store/sale-items' => 'products#sale_items', :as => :sale_items

  resources :boxes, path: '/store/boxes'
  resources :shipments, path: '/store/shipments'
  resources :addresses, path: '/store/users/addresses'
  resource :cart, only: [:show], path: '/store/cart'
  resource :checkout, path: '/store/checkout'
  resources :items, path: '/store/items'
  resources :orders, path: '/store/orders'
  devise_for :users, path: '/store/users', controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  resources :users, path: '/store/users', only: [:show, :index, :destroy]
  resources :photos, path: '/store/photos'
  resources :products, path: '/store'
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]

  root 'showcase#home'
  get '/alchemist-series/avani.odt' => 'showcase#download_avani', :as => :avani
  get '/alchemist-series/ember.odt' => 'showcase#download_ember', :as => :ember
  get '/alchemist-series/zephyr.odt' => 'showcase#download_zephyr', :as => :zephyr
  get '/alchemist-series' => 'showcase#alchemist_series', :as => :alchemist_series
  get '/about' => 'showcase#about', :as => :about
  get '/boddington-rifle-project' => 'showcase#boddington_rifle_project', :as => :boddington_rifle_project
  get '/bracelet-helpers' => 'showcase#bracelet_helpers', :as => :bracelet_helpers
  get '/contact' => 'showcase#contact', :as => :contact
  get '/custom-rifles' => 'showcase#custom_rifles', :as => :custom_rifles
  get '/engraving' => 'showcase#engraving', :as => :engraving
  get '/events' => 'showcase#events', :as => :events
  get '/finishes' => 'showcase#finishes', :as => :finishes
  get '/gun-fitting' => 'showcase#gun_fitting', :as => :gun_fitting
  get '/gun-parts' => 'showcase#gun_parts', :as => :gun_parts
  get '/guns-for-sale' => 'showcase#guns_for_sale', :as => :guns_for_sale
  get '/gunsmithing' => 'showcase#gunsmithing', :as => :gunsmithing
  get '/home' => 'showcase#home', :as => :home
  get '/key-chains' => 'showcase#key_chains', :as => :key_chains
  get '/leather-wrap-pads' => 'showcase#leather_wrap_pads', :as => :leather_wrap_pads
  get '/media' => 'showcase#media', :as => :media
  get '/payment-and-shipping' => 'showcase#payment_and_shipping', :as => :payment_and_shipping
  get '/pistols' => 'showcase#pistols', :as => :pistols
  get '/pens' => 'showcase#pens', :as => :pens
  get '/restoration' => 'showcase#restoration', :as => :restoration
  get '/shotguns' => 'showcase#shotguns', :as => :shotguns
  get '/stock-work' => 'showcase#stock_work', :as => :stock_work
  get '/synthetic-rifles' => 'showcase#synthetic_rifles', :as => :synthetic_rifles
  get '/taylors-pens-and-gifts' => 'showcase#taylors_pens_and_gifts', :as => :taylors_pens_and_gifts
  get '/trophy-room' => 'showcase#trophy_room', :as => :trophy_room
  get '/wine-stoppers' => 'showcase#wine_stoppers', :as => :wine_stoppers

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :products]
  before_action :update_on_sale, only: [:show]
  layout 'store'

  # GET /products
  def index
    @products = Product.where('active = ? or active = ?', true, !current_user.admin)
    @products = @products.order('created_at desc') if params[:qorder]
    filtering_params(params).each do |key, value|
      @products = @products.public_send(key, value) if value.present?
    end
    @no_page = @products
    @products = Kaminari.paginate_array(@products).page(params[:page]).per(16)
  end


  def main
    @primary = Tile.where(show: true, group: "primary").order(:major, :minor)
    @tiles = Tile.where.not(show: false, group: "primary").order(:major, :minor).group_by(&:group)
    @products = Product.where(active: true).order('RANDOM()').limit(4)
  end

  def products
    redirect_to products_url
    #@grid = initialize_grid(Product, include: :photos, order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def gun_parts
    redirect_to products_url(:department => 'gun_parts')
    #@gun_parts_grid = initialize_grid(Product.where(store: 'gun_parts', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def wood
    redirect_to products_url(:department => 'wood')
    #@wood_grid = initialize_grid(Product.where(store: 'wood', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def barrels
    redirect_to products_url(:department => 'barrels')
    #@barrels_grid = initialize_grid(Product.where(store: 'barrels', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def optics
    redirect_to products_url(:department => 'optics')
    #@optics_grid = initialize_grid(Product.where(store: 'optics', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def gifts
    redirect_to products_url(:department => 'gifts')
    #@gifts_grid = initialize_grid(Product.where(store: 'gifts', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def jewelry
    redirect_to products_url(:department => 'jewelry')
    #@jewelry_grid = initialize_grid(Product.where(store: 'jewelry', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def decor
    redirect_to products_url(:department => 'decor')
    #@decor_grid = initialize_grid(Product.where(store: 'decor', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def gun_cases
    redirect_to products_url(:department => 'gun_cases')
    #@gun_cases_grid = initialize_grid(Product.where(store: 'gun_cases', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def guns
    redirect_to products_url(:department => 'guns')
    #@guns_grid = initialize_grid(Product.where(store: 'guns', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def custom_parts
    redirect_to products_url(:department => 'custom_parts')
    #@custom_parts_grid = initialize_grid(Product.where(store: 'custom_parts', active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def new_arrivals
    redirect_to products_url(:qorder => 't')
    #@products = Product.where(active: true).limit(60).order('created_at DESC')
    #@range = @products.last.created_at..@products.first.created_at
    #@new_arrivals_grid = initialize_grid(Product.where(active: true, created_at: @range), order: 'products.created_at', order_direction: 'desc', per_page: 20)
  end

  def sale_items
    redirect_to products_url(:qsale => 't')
    #@sales_grid = initialize_grid(Product.where(sale: true, active: true), order: 'products.title', order_direction: 'asc', per_page: 20)
  end

  def privacy_policy
  end

  def return_policy
  end

  def terms_and_conditions
  end

  def payment_policy
  end

  def shipping_policy
  end

  def sales_tax
  end

  def contact
  end

  def update_on_sale
    @product.update_on_sale
  end

  def filtering_params(params)
    params.slice(:department, :search, :qmodel, :qmanufacturer, :qpart_number,
                 :qmaterial, :qcaliber, :qbarrel_length, :qtype_field,
                 :qstyle_field, :qfield_of_view_low_power, :qsale,
                 :qfield_of_view_high_power, :qdiopter_adjustment, :qeye_relief,
                 :qexit_pupil_low_power,:qexit_pupil_high_power,
                 :qelevation_travel, :qwindage_travel, :qmoa_per_click_upper,
                 :qmoa_per_click_lower, :qparallax_compensation, :qtotal_travel,
                 :qtube_diameter, :qposition_of_reticle, :qavailable_reticles)
  end

  # GET /products/1
  def show
    @item = Item.new
    @photos = @product.photos.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @photos = @product.photos.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    unless params[:new_store].empty?
      @product.store = params[:new_store]
    end
    if @product.save
      save_attachments if params[:photos]
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    update_attachments if params[:photos]
    unless params[:new_store].empty?
      params[:product][:store] = params[:new_store]
    end
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.photos.each(&:destroy)
    @product.destroy
    redirect_to product_management_path, notice: 'Product was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def product_params
    params.require(:product).permit(:title, :manufacturer, :model,
                                    :part_number, :price, :quantity,
                                    :description, :images, :schematic,
                                    :weight, :height, :width, :length, :tags,
                                    :categories, :exclusive, :store, :material,
                                    :caliber, :barrel_length, :type_field,
                                    :style_field, :active, :shipped_by, :sale,
                                    :sale_price, :field_of_view_low_power,
                                    :field_of_view_high_power,
                                    :diopter_adjustment, :eye_relief,
                                    :exit_pupil_low_power,
                                    :exit_pupil_high_power, :elevation_travel,
                                    :windage_travel, :moa_per_click_upper,
                                    :moa_per_click_lower,
                                    :parallax_compensation, :total_travel,
                                    :tube_diameter, :position_of_reticle,
                                    :available_reticles,
                                    :sale_end,
                                    :shipper_id, :has_box,
                                    :shipping_height, :shipping_width,
                                    :shipping_length, :shipping_weight,
                                    :compressible,
                                    :new_store,
                                    product_attachments_attributes:
                                      [:id, :product_id, :image])
  end

  def save_attachments
    params[:photos]['image'].each do |a|
      @photo = @product.photos.create!(image: a, product_id: @product.id)
    end
  end

  def update_attachments
    @product.photos.each(&:destroy) if @product.photos.present?
    params[:photos]['image'].each do |a|
      @photo = @product.photos.create!(image: a, product_id: @product.id)
    end
 end
end

app/helpers/products_helper.rb
module ProductsHelper
  def m_yd(value)
    value.round(0).to_s + ' m / ' + (value * 1.0936).round(0).to_s + ' yd'
  end

  def mm_thou(value)
    value.round(1).to_s + ' mm / ' + (value * 39.3701).round(1).to_s + ' thou'
  end

  def dimensions_as_m(product)
    buffer = (product.length / 100).to_s + ' x '
    buffer += (product.width / 100).to_s + ' x '
    buffer += (product.height / 100).to_s + ' m.'
    buffer
  end

  def dimensions_as_cm(length, width, height)
    buffer = length.to_s + ' x '
    buffer += width.to_s + ' x '
    buffer += height.to_s + ' cm.'
    buffer
  end

  def dimensions_as_inches(length, width, height)
    buffer = (length / 2.54).round(2).to_s + ' x '
    buffer += (width / 2.54).round(2).to_s + ' x '
    buffer += (height / 2.54).round(2).to_s + ' in.'
    buffer
  end

  def weight_as_metric(weight)
    if weight < 1000
      weight.to_s + ' g.'
    else
      (weight / 1000).round(0).to_s + ' kg.'
    end
  end

  def weight_as_imperial(weight)
    weight = (((weight / 1000) * 35.274) / 16)
    pounds = weight.floor
    weight -= pounds

    ounces = (weight * 16).floor
    weight -= ounces / 16

    drachm = (weight * 256).floor
    weight -= drachm / 256

    grains = (weight * 7000).floor

    buffer = ''

    if pounds >= 1
      (buffer += pounds.to_s + ' lb. ')
    end

    if ounces >= 1
      (buffer += ounces.to_s + ' oz. ')
    end

    if drachm >= 1 && pounds < 1
      (buffer += drachm.to_s + ' dr. ')
    end

    if grains >= 1 && pounds < 1 && ounces < 1
      (buffer += grains.to_s + ' gr. ')
    end

    buffer
  end

  def get_shipping_phase(order)
    case order.phase
    when 0
      "Initial"
    when 2
      "Address Selection"
    when 3
      "Shipping Selection"
    when 4
      "Order Review"
    when 5
      "Payment Processing"
    else
      "Initial"
    end
  end
end

app/views/products/main.html.haml
- unless @primary.empty?
  #mainCarousel.carousel.slide{"data-ride" => "carousel", style:" background: white; width: 100%;"}
    %ol.carousel-indicators
      - @primary.each_with_index do |p, i|
        %li{"data-slide-to" => i, "data-target" => "#mainCarousel", class: "#{'active' if i == 0}"}
    .carousel-inner
      - @primary.each_with_index do |p, i|
        .item{class: "#{'active' if i == 0}"}
          %a{:href => p.url}
            %img{:alt => "#{p.title}",
                 :src => p.image.blank? ? "http://via.placeholder.com/1200x450" : p.image,
                 :style => "width:100%;"}/
            .carousel-caption
              %b= p.title
              %p= p.text
    %a.left.carousel-control{"data-slide" => "prev", :href => "#mainCarousel"}
      %span.glyphicon.glyphicon-chevron-left
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#mainCarousel"}
      %span.glyphicon.glyphicon-chevron-right
      %span.sr-only Next
- @tiles.each do |group, tile_group|
  .page-header
    %center
      %h3="《#{group.to_s.titleize}》"
  .well
    - tile_group.in_groups_of(4, false).each do |tiles|
      -if tiles.count == 2
        - scale = "col-lg-6 col-md-6 col-sm-6 col-xs-6"
      -elsif tiles.count == 3
        - scale = "col-lg-4 col-md-4 col-sm-4 col-xs-6"
      -else
        - scale = "col-lg-3 col-md-3 col-sm-3 col-xs-6"
      .row
        -tiles.each do |tile|
          %div{class: scale}
            .widewrapper=link_to(image_tag(tile.image.blank? ? "http://via.placeholder.com/350x350" : tile.image), tile.url)
            %br
/.row
/  .col-md-4.col-sm-4.col-xs-12
/    .widewrapper=link_to(image_tag("theme/store_default/barrels.png"), barrels_path)
/    %br
/  .col-md-4.col-sm-4.col-xs-12
/    .widewrapper=link_to(image_tag("theme/store_default/custom_parts.png"), custom_parts_path)
/    %br
/  .col-md-4.col-sm-4.col-xs-12
/    .widewrapper=link_to(image_tag("theme/store_default/decor.png"), decor_path)
/    %br
/.page-header
/  %h1 Store
/.well
/
/  .row
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/gifts.png"), gifts_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/gun_cases.png"), gun_cases_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/gun_parts.png"), gunparts_path)
/      %p
/  .row
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/guns.png"), guns_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/jewelry.png"), jewelry_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/new_arrivals.png"), new_arrivals_path)
/      %p
/  .row
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/optics.png"), optics_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/sale_items.png"), sale_items_path)
/      %p
/    .col-md-4.col-sm-4.col-xs-12
/      .widewrapper=link_to(image_tag("theme/store_default/wood.png"), wood_path)
/      %p
.page-header
  %center
    %h3 《Featured Products》
.well
  =render :partial => 'entries', :locals => {products: @products}
:javascript
  $(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
  });

app/views/products/return_policy.html.haml
- content_for :title,  "Return Policy"
.page-header
  %h1 Return Policy
  %h3
    Returns, Refunds and Exchanges Policy
%p
How To Return An Item
Your item must be in its original unused condition to be returned, unless there is a manufacturer defect. You must return the item within 15 days of your purchase.
%br
%br
1. Please email customgun.tr@gmail.com  to request a refund and we will assign you a tracking #.
%br
%br
2. Mail your returned item to:
%br Custom Shop LLC
Returns Department Tracking #
7680 North U.S. Highway 69
Alba, Texas 75410
%br
%br
3. Include in your package a signed letter stating the reason for your return and the original receipt.
%h3
  Return Exceptions
%p
  Some items can not be returned if they are opened. These include music, software, and video games.

  Merchandise that has been worn, used, or altered will not be accepted for return or exchange.
  %h3
    Restocking Fee
%p
All items are subject to a 20% restocking fee, this will be deducted from your refund. We also do not refund the original shipping and handling that you paid on the order.
%h3
  Exchanges
%p
  If your clothing item is in like new condition, you may exchange your clothing item for a different size or color. You will not be subject to a restocking fee in this case, but you still will have to pay return shipping.
  %h3
    Gun Part Policy
%p
You may return unaltered items purchased through Custom Shop, LLC within 15 days of purchase for an exchange, refund, or store credit. An unaltered item means that no modification such as grinding, fitting, drilling, sanding, chemical cleaning, restoration, painting or other changes of any kind has occurred. Altered products or products in abused condition will be returned to the customer at their expense.
Should you need to return an item please contact us at customgun.tr@gmail.com or call us at 903-768-2948. We will do our best to resolve any issue and answer any questions before a return is needed. Many of our customers find that having a few questions answered prior to the return of a product may resolve the issues they encounter.
We try our best to select and ship the correct item(s) in each order. Unfortunately, selection errors are sometimes made and not caught prior to shipping. In the event the error is caused by Custom Shop, LLC, we will refund your return shipping cost up to the original invoice shipping charge. If this is not the case the buyer may be responsible for all shipping costs associated with any return or exchange. We do not refund for additional services such as Delivery Confirmation, Insurance, etc. Please properly package the return to the address listed below and we will be happy to contact you by phone or e-mail when we receive the package. Include a copy of the original invoice or the original order number and daytime customer contact information in your return.
%p
  %br
  ATTN: Customer Service
  %br
  Custom Shop, LLC
  %br
  7680 North U.S. Highway 69
  %br
  Alba, Texas 75410

app/views/products/shipping_policy.html.haml
- content_for :title,  "Shipping Policy"
.page-header
  %h1 Shipping Policy
%h2
  Turnaround
%p

  All orders are shipped within 72 hours Monday - Friday 8am - 5pm.
%h2
  Carriers

%p
  We use the following carriers to deliver our orders:

%h4
  USPS
%h4
  FedEx
%h2
  Order Tracking
%p
If a tracking # is provided by the shipping carrier, we will update your order with the tracking information. Please note that some orders using 1st Class USPS mail will not have tracking numbers.
%h2
  Shipping Rates
%p
The rate charged for the shipping of your order is based on the weight of your products, and your location. Before the final checkout page you will be shown what the cost of shipping will be, and you will have a chance to not place your order if you decide not to.
%h2
  Shipping/Delivery Area
%p
We ship orders to physical addresses within the 50 United States. We require a physical address for delivery, therefore we cannot fulfill orders shipping to AFO (Armed Forces Oversees) and FPO (Fleet Post Office), or to U.S. Post Office Box addresses.
Online ordering is only available for shipments going to the contiguous U.S. If you are shipping to Hawaii, Alaska, or one of the U.S. territories, please call Customer Service at 903-768-2948 to place your order. Customer Service hours are Monday through Friday, 9 a.m. to 5 p.m. Eastern Time (CST).
%br
%h2 Gun Part Shiping
%p All gun parts are shipped in boxes. Padded envelopes allow the parts to pierce through the package and often result in loss of part along the way.
%h2
  Scope Shipping
%p
  Attention customers: We do not ship rifle scopes internationally.  Address, we ship scopes to must match your billing address on your credit card.
%h2
  Gun Shipping
%br
%p
**PLEASE NOTE: All Firearms MUST be shipped to Licensed Firearms Dealer. We will contact you for a copy of the FFL that you would like to use to transfer this firearm. **
%br

%h2
  International Orders
%p
We are presently unable to ship orders outside the United States.

%h2
  Back Orders
%p
If an item goes on back order we will ship you the part of your order that is in stock. When the item becomes available we will ship you the rest of your order. You will not be charged any additional shipping and handling for the second shipment.
%br
%br